export type Language = (typeof languages)[number];

export const languageCodeToName = (code: string | null) =>
  languages.find((l) => l.code === code)?.englishName || code;

/**
 * ISO 639 language codes
 * https://stackoverflow.com/a/20623472
 */
export const languages = [
  { code: 'ab', englishName: 'Abkhaz', nativeName: 'аҧсуа' },
  { code: 'aa', englishName: 'Afar', nativeName: 'Afaraf' },
  { code: 'af', englishName: 'Afrikaans', nativeName: 'Afrikaans' },
  { code: 'ak', englishName: 'Akan', nativeName: 'Akan' },
  { code: 'sq', englishName: 'Albanian', nativeName: 'Shqip' },
  { code: 'am', englishName: 'Amharic', nativeName: 'አማርኛ' },
  { code: 'ar', englishName: 'Arabic', nativeName: 'العربية' },
  { code: 'an', englishName: 'Aragonese', nativeName: 'Aragonés' },
  { code: 'hy', englishName: 'Armenian', nativeName: 'Հայերեն' },
  { code: 'as', englishName: 'Assamese', nativeName: 'অসমীয়া' },
  { code: 'av', englishName: 'Avaric', nativeName: 'авар мацӀ, магӀарул мацӀ' },
  { code: 'ae', englishName: 'Avestan', nativeName: 'avesta' },
  { code: 'ay', englishName: 'Aymara', nativeName: 'aymar aru' },
  { code: 'az', englishName: 'Azerbaijani', nativeName: 'azərbaycan dili' },
  { code: 'bm', englishName: 'Bambara', nativeName: 'bamanankan' },
  { code: 'ba', englishName: 'Bashkir', nativeName: 'башҡорт теле' },
  { code: 'eu', englishName: 'Basque', nativeName: 'euskara, euskera' },
  { code: 'be', englishName: 'Belarusian', nativeName: 'Беларуская' },
  { code: 'bn', englishName: 'Bengali', nativeName: 'বাংলা' },
  { code: 'bh', englishName: 'Bihari', nativeName: 'भोजपुरी' },
  { code: 'bi', englishName: 'Bislama', nativeName: 'Bislama' },
  { code: 'bs', englishName: 'Bosnian', nativeName: 'bosanski jezik' },
  { code: 'br', englishName: 'Breton', nativeName: 'brezhoneg' },
  { code: 'bg', englishName: 'Bulgarian', nativeName: 'български език' },
  { code: 'my', englishName: 'Burmese', nativeName: 'ဗမာစာ' },
  { code: 'ca', englishName: 'Catalan; Valencian', nativeName: 'Català' },
  { code: 'ch', englishName: 'Chamorro', nativeName: 'Chamoru' },
  { code: 'ce', englishName: 'Chechen', nativeName: 'нохчийн мотт' },
  { code: 'ny', englishName: 'Chichewa; Chewa; Nyanja', nativeName: 'chiCheŵa, chinyanja' },
  { code: 'zh', englishName: 'Chinese', nativeName: '中文 (Zhōngwén), 汉语, 漢語' },
  { code: 'cv', englishName: 'Chuvash', nativeName: 'чӑваш чӗлхи' },
  { code: 'kw', englishName: 'Cornish', nativeName: 'Kernewek' },
  { code: 'co', englishName: 'Corsican', nativeName: 'corsu, lingua corsa' },
  { code: 'cr', englishName: 'Cree', nativeName: 'ᓀᐦᐃᔭᐍᐏᐣ' },
  { code: 'hr', englishName: 'Croatian', nativeName: 'hrvatski' },
  { code: 'cs', englishName: 'Czech', nativeName: 'česky, čeština' },
  { code: 'da', englishName: 'Danish', nativeName: 'dansk' },
  { code: 'dv', englishName: 'Divehi; Dhivehi; Maldivian;', nativeName: 'ދިވެހި' },
  { code: 'nl', englishName: 'Dutch', nativeName: 'Nederlands, Vlaams' },
  { code: 'en', englishName: 'English', nativeName: 'English' },
  { code: 'eo', englishName: 'Esperanto', nativeName: 'Esperanto' },
  { code: 'et', englishName: 'Estonian', nativeName: 'eesti, eesti keel' },
  { code: 'ee', englishName: 'Ewe', nativeName: 'Eʋegbe' },
  { code: 'fo', englishName: 'Faroese', nativeName: 'føroyskt' },
  { code: 'fj', englishName: 'Fijian', nativeName: 'vosa Vakaviti' },
  { code: 'fi', englishName: 'Finnish', nativeName: 'suomi, suomen kieli' },
  { code: 'fr', englishName: 'French', nativeName: 'français, langue française' },
  { code: 'ff', englishName: 'Fula; Fulah; Pulaar; Pular', nativeName: 'Fulfulde, Pulaar, Pular' },
  { code: 'gl', englishName: 'Galician', nativeName: 'Galego' },
  { code: 'ka', englishName: 'Georgian', nativeName: 'ქართული' },
  { code: 'de', englishName: 'German', nativeName: 'Deutsch' },
  { code: 'el', englishName: 'Greek, Modern', nativeName: 'Ελληνικά' },
  { code: 'gn', englishName: 'Guaraní', nativeName: 'Avañeẽ' },
  { code: 'gu', englishName: 'Gujarati', nativeName: 'ગુજરાતી' },
  { code: 'ht', englishName: 'Haitian; Haitian Creole', nativeName: 'Kreyòl ayisyen' },
  { code: 'ha', englishName: 'Hausa', nativeName: 'Hausa, هَوُسَ' },
  { code: 'he', englishName: 'Hebrew (modern)', nativeName: 'עברית' },
  { code: 'hz', englishName: 'Herero', nativeName: 'Otjiherero' },
  { code: 'hi', englishName: 'Hindi', nativeName: 'हिन्दी, हिंदी' },
  { code: 'ho', englishName: 'Hiri Motu', nativeName: 'Hiri Motu' },
  { code: 'hu', englishName: 'Hungarian', nativeName: 'Magyar' },
  { code: 'ia', englishName: 'Interlingua', nativeName: 'Interlingua' },
  { code: 'id', englishName: 'Indonesian', nativeName: 'Bahasa Indonesia' },
  {
    code: 'ie',
    englishName: 'Interlingue',
    nativeName: 'Originally called Occidental; then Interlingue after WWII',
  },
  { code: 'ga', englishName: 'Irish', nativeName: 'Gaeilge' },
  { code: 'ig', englishName: 'Igbo', nativeName: 'Asụsụ Igbo' },
  { code: 'ik', englishName: 'Inupiaq', nativeName: 'Iñupiaq, Iñupiatun' },
  { code: 'io', englishName: 'Ido', nativeName: 'Ido' },
  { code: 'is', englishName: 'Icelandic', nativeName: 'Íslenska' },
  { code: 'it', englishName: 'Italian', nativeName: 'Italiano' },
  { code: 'iu', englishName: 'Inuktitut', nativeName: 'ᐃᓄᒃᑎᑐᑦ' },
  { code: 'ja', englishName: 'Japanese', nativeName: '日本語 (にほんご／にっぽんご)' },
  { code: 'jv', englishName: 'Javanese', nativeName: 'basa Jawa' },
  {
    code: 'kl',
    englishName: 'Kalaallisut, Greenlandic',
    nativeName: 'kalaallisut, kalaallit oqaasii',
  },
  { code: 'kn', englishName: 'Kannada', nativeName: 'ಕನ್ನಡ' },
  { code: 'kr', englishName: 'Kanuri', nativeName: 'Kanuri' },
  { code: 'ks', englishName: 'Kashmiri', nativeName: 'कश्मीरी, كشميري‎' },
  { code: 'kk', englishName: 'Kazakh', nativeName: 'Қазақ тілі' },
  { code: 'km', englishName: 'Khmer', nativeName: 'ភាសាខ្មែរ' },
  { code: 'ki', englishName: 'Kikuyu, Gikuyu', nativeName: 'Gĩkũyũ' },
  { code: 'rw', englishName: 'Kinyarwanda', nativeName: 'Ikinyarwanda' },
  { code: 'ky', englishName: 'Kirghiz, Kyrgyz', nativeName: 'кыргыз тили' },
  { code: 'kv', englishName: 'Komi', nativeName: 'коми кыв' },
  { code: 'kg', englishName: 'Kongo', nativeName: 'KiKongo' },
  { code: 'ko', englishName: 'Korean', nativeName: '한국어 (韓國語), 조선말 (朝鮮語)' },
  { code: 'ku', englishName: 'Kurdish', nativeName: 'Kurdî, كوردی‎' },
  { code: 'kj', englishName: 'Kwanyama, Kuanyama', nativeName: 'Kuanyama' },
  { code: 'la', englishName: 'Latin', nativeName: 'latine, lingua latina' },
  { code: 'lb', englishName: 'Luxembourgish, Letzeburgesch', nativeName: 'Lëtzebuergesch' },
  { code: 'lg', englishName: 'Luganda', nativeName: 'Luganda' },
  { code: 'li', englishName: 'Limburgish, Limburgan, Limburger', nativeName: 'Limburgs' },
  { code: 'ln', englishName: 'Lingala', nativeName: 'Lingála' },
  { code: 'lo', englishName: 'Lao', nativeName: 'ພາສາລາວ' },
  { code: 'lt', englishName: 'Lithuanian', nativeName: 'lietuvių kalba' },
  { code: 'lu', englishName: 'Luba-Katanga', nativeName: '' },
  { code: 'lv', englishName: 'Latvian', nativeName: 'latviešu valoda' },
  { code: 'gv', englishName: 'Manx', nativeName: 'Gaelg, Gailck' },
  { code: 'mk', englishName: 'Macedonian', nativeName: 'македонски јазик' },
  { code: 'mg', englishName: 'Malagasy', nativeName: 'Malagasy fiteny' },
  { code: 'ms', englishName: 'Malay', nativeName: 'bahasa Melayu, بهاس ملايو‎' },
  { code: 'ml', englishName: 'Malayalam', nativeName: 'മലയാളം' },
  { code: 'mt', englishName: 'Maltese', nativeName: 'Malti' },
  { code: 'mi', englishName: 'Māori', nativeName: 'te reo Māori' },
  { code: 'mr', englishName: 'Marathi (Marāṭhī)', nativeName: 'मराठी' },
  { code: 'mh', englishName: 'Marshallese', nativeName: 'Kajin M̧ajeļ' },
  { code: 'mn', englishName: 'Mongolian', nativeName: 'монгол' },
  { code: 'na', englishName: 'Nauru', nativeName: 'Ekakairũ Naoero' },
  { code: 'nv', englishName: 'Navajo, Navaho', nativeName: 'Diné bizaad, Dinékʼehǰí' },
  { code: 'nb', englishName: 'Norwegian Bokmål', nativeName: 'Norsk bokmål' },
  { code: 'nd', englishName: 'North Ndebele', nativeName: 'isiNdebele' },
  { code: 'ne', englishName: 'Nepali', nativeName: 'नेपाली' },
  { code: 'ng', englishName: 'Ndonga', nativeName: 'Owambo' },
  { code: 'nn', englishName: 'Norwegian Nynorsk', nativeName: 'Norsk nynorsk' },
  { code: 'no', englishName: 'Norwegian', nativeName: 'Norsk' },
  { code: 'ii', englishName: 'Nuosu', nativeName: 'ꆈꌠ꒿ Nuosuhxop' },
  { code: 'nr', englishName: 'South Ndebele', nativeName: 'isiNdebele' },
  { code: 'oc', englishName: 'Occitan', nativeName: 'Occitan' },
  { code: 'oj', englishName: 'Ojibwe, Ojibwa', nativeName: 'ᐊᓂᔑᓈᐯᒧᐎᓐ' },
  {
    code: 'cu',
    englishName: 'Old Church Slavonic, Church Slavic, Church Slavonic, Old Bulgarian, Old Slavonic',
    nativeName: 'ѩзыкъ словѣньскъ',
  },
  { code: 'om', englishName: 'Oromo', nativeName: 'Afaan Oromoo' },
  { code: 'or', englishName: 'Oriya', nativeName: 'ଓଡ଼ିଆ' },
  { code: 'os', englishName: 'Ossetian, Ossetic', nativeName: 'ирон æвзаг' },
  { code: 'pa', englishName: 'Panjabi, Punjabi', nativeName: 'ਪੰਜਾਬੀ, پنجابی‎' },
  { code: 'pi', englishName: 'Pāli', nativeName: 'पाऴि' },
  { code: 'fa', englishName: 'Persian', nativeName: 'فارسی' },
  { code: 'pl', englishName: 'Polish', nativeName: 'polski' },
  { code: 'ps', englishName: 'Pashto, Pushto', nativeName: 'پښتو' },
  { code: 'pt', englishName: 'Portuguese', nativeName: 'Português' },
  { code: 'qu', englishName: 'Quechua', nativeName: 'Runa Simi, Kichwa' },
  { code: 'rm', englishName: 'Romansh', nativeName: 'rumantsch grischun' },
  { code: 'rn', englishName: 'Kirundi', nativeName: 'kiRundi' },
  { code: 'ro', englishName: 'Romanian, Moldavian, Moldovan', nativeName: 'română' },
  { code: 'ru', englishName: 'Russian', nativeName: 'русский язык' },
  { code: 'sa', englishName: 'Sanskrit (Saṁskṛta)', nativeName: 'संस्कृतम्' },
  { code: 'sc', englishName: 'Sardinian', nativeName: 'sardu' },
  { code: 'sd', englishName: 'Sindhi', nativeName: 'सिन्धी, سنڌي، سندھی‎' },
  { code: 'se', englishName: 'Northern Sami', nativeName: 'Davvisámegiella' },
  { code: 'sm', englishName: 'Samoan', nativeName: 'gagana faa Samoa' },
  { code: 'sg', englishName: 'Sango', nativeName: 'yângâ tî sängö' },
  { code: 'sr', englishName: 'Serbian', nativeName: 'српски језик' },
  { code: 'gd', englishName: 'Scottish Gaelic; Gaelic', nativeName: 'Gàidhlig' },
  { code: 'sn', englishName: 'Shona', nativeName: 'chiShona' },
  { code: 'si', englishName: 'Sinhala, Sinhalese', nativeName: 'සිංහල' },
  { code: 'sk', englishName: 'Slovak', nativeName: 'slovenčina' },
  { code: 'sl', englishName: 'Slovene', nativeName: 'slovenščina' },
  { code: 'so', englishName: 'Somali', nativeName: 'Soomaaliga, af Soomaali' },
  { code: 'st', englishName: 'Southern Sotho', nativeName: 'Sesotho' },
  { code: 'es', englishName: 'Spanish; Castilian', nativeName: 'español, castellano' },
  { code: 'su', englishName: 'Sundanese', nativeName: 'Basa Sunda' },
  { code: 'sw', englishName: 'Swahili', nativeName: 'Kiswahili' },
  { code: 'ss', englishName: 'Swati', nativeName: 'SiSwati' },
  { code: 'sv', englishName: 'Swedish', nativeName: 'svenska' },
  { code: 'ta', englishName: 'Tamil', nativeName: 'தமிழ்' },
  { code: 'te', englishName: 'Telugu', nativeName: 'తెలుగు' },
  { code: 'tg', englishName: 'Tajik', nativeName: 'тоҷикӣ, toğikī, تاجیکی‎' },
  { code: 'th', englishName: 'Thai', nativeName: 'ไทย' },
  { code: 'ti', englishName: 'Tigrinya', nativeName: 'ትግርኛ' },
  { code: 'bo', englishName: 'Tibetan Standard, Tibetan, Central', nativeName: 'བོད་ཡིག' },
  { code: 'tk', englishName: 'Turkmen', nativeName: 'Türkmen, Түркмен' },
  { code: 'tl', englishName: 'Tagalog', nativeName: 'Wikang Tagalog, ᜏᜒᜃᜅ᜔ ᜆᜄᜎᜓᜄ᜔' },
  { code: 'tn', englishName: 'Tswana', nativeName: 'Setswana' },
  { code: 'to', englishName: 'Tonga (Tonga Islands)', nativeName: 'faka Tonga' },
  { code: 'tr', englishName: 'Turkish', nativeName: 'Türkçe' },
  { code: 'ts', englishName: 'Tsonga', nativeName: 'Xitsonga' },
  { code: 'tt', englishName: 'Tatar', nativeName: 'татарча, tatarça, تاتارچا‎' },
  { code: 'tw', englishName: 'Twi', nativeName: 'Twi' },
  { code: 'ty', englishName: 'Tahitian', nativeName: 'Reo Tahiti' },
  { code: 'ug', englishName: 'Uighur, Uyghur', nativeName: 'Uyƣurqə, ئۇيغۇرچە‎' },
  { code: 'uk', englishName: 'Ukrainian', nativeName: 'українська' },
  { code: 'ur', englishName: 'Urdu', nativeName: 'اردو' },
  { code: 'uz', englishName: 'Uzbek', nativeName: 'zbek, Ўзбек, أۇزبېك‎' },
  { code: 've', englishName: 'Venda', nativeName: 'Tshivenḓa' },
  { code: 'vi', englishName: 'Vietnamese', nativeName: 'Tiếng Việt' },
  { code: 'vo', englishName: 'Volapük', nativeName: 'Volapük' },
  { code: 'wa', englishName: 'Walloon', nativeName: 'Walon' },
  { code: 'cy', englishName: 'Welsh', nativeName: 'Cymraeg' },
  { code: 'wo', englishName: 'Wolof', nativeName: 'Wollof' },
  { code: 'fy', englishName: 'Western Frisian', nativeName: 'Frysk' },
  { code: 'xh', englishName: 'Xhosa', nativeName: 'isiXhosa' },
  { code: 'yi', englishName: 'Yiddish', nativeName: 'ייִדיש' },
  { code: 'yo', englishName: 'Yoruba', nativeName: 'Yorùbá' },
  { code: 'za', englishName: 'Zhuang, Chuang', nativeName: 'Saɯ cueŋƅ, Saw cuengh' },
];
